### ISSUE TITLE
Artifacts in some cases

### ISSUE THREAD

**Issue by msiglreith** [glowcoil/gouache#1]
During implementation in my cpu rasterizer, I noticed some artifacts in certain edge cases:
I managed to reproduce them as well with your gpu implementation (https://github.com/msiglreith/gouache/tree/issue01): `cargo run --example issue01`

![grafik](https://user-images.githubusercontent.com/7253845/73592214-316c9800-44f8-11ea-9e69-665cfd0769a7.png)

It's more apparent when doing the raycasts in y-direction for normal text cases (runic example):
![grafik](https://user-images.githubusercontent.com/7253845/73592326-501f5e80-44f9-11ea-97c4-de6d3e35b4cd.png)

I'm currently debugging on what exactly causes this 👀

**Comment by msiglreith** [comment]
It seems to be that the current implementation can't guarentee that the different coverage values will cancel out in these corner cases due to the weighting.

**Comment by glowcoil** [comment]
Thanks for finding and pointing this out! I think you're right about what causes it. What's happening for those near-horizontal segments (or near-vertical, in runic) is that pixels which don't intersect the curve, and thus should only be getting a partial y-coverage (or x-coverage, in runic), do intersect the tangent-line approximation since the slope of the curve is so small.

A principled way to fix this would be to shoot two rays, at the top and bottom of the overlapping y-range, and find the actual overlap of this trapezoid with the pixel footprint. However, I was able to fix the artifact more cheaply. Currently, the shader avoids computing the contribution of a curve if its AABB is fully to the left of the pixel footprint, but it still computes horizontal overlap if the AABB is fully to the right. I changed it to treat horizontal overlap as 1.0 if the AABB is fully to the right, and the artifact went away:

![image](https://user-images.githubusercontent.com/131388/73614837-7233e200-45c8-11ea-860b-ddb8adcc59f1.png)

Incidentally, I had the code for this lying around somewhere and was planning to commit it anyway, since it turned out to be a slight optimization. I will definitely commit it now that it's necessary to avoid artifacts.

One more thing: notice how the artifact only appeared to the left of the path in gouache, whereas it appears both above and below in runic's version. I'm assuming that's because you compute overlap along the ray even when the curve's AABB is fully above or below the pixel. You would be able to fix this artifact by doing the same check, and in the CPU case I imagine it would be even more of a speedup.
